version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Direct environment variable definition
      - ENV_VAR_NAME=value
    env_file:
      # External environment file
      - .env
    ports:
      # Correct port mapping
      - "8080:80"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"